name: Scan code with Snyk and Archive if Secure

on: 
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      
      # Paso para ejecutar Snyk y verificar vulnerabilidades
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # Asegura que se pueda subir el resultado incluso si Snyk falla
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif --all-projects

      # Subir el informe de Snyk a GitHub Code Scanning
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      # Condicional para archivar el código solo si no se encuentran vulnerabilidades críticas o severas
      - name: Create zip
        if: success() # Solo si los pasos anteriores fueron exitosos
        uses: ihiroky/archive-action@v1
        with:
          root_dir: ./ # Este es el directorio raíz que quieres archivar
          file_path: secure-code.zip # Aquí defines el nombre y la ruta del archivo ZIP

